// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaCZSXYX0EsbT6I8I84JJs5mlxsbZsnz0',
    appId: '1:963645050762:web:b79d86da947b94d2d58273',
    messagingSenderId: '963645050762',
    projectId: 'abstask-9bba7',
    authDomain: 'abstask-9bba7.firebaseapp.com',
    storageBucket: 'abstask-9bba7.firebasestorage.app',
    measurementId: 'G-JDTTQ30NVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTjLFmxZJtRASomsq0cJp6W0_ByEGIfZ4',
    appId: '1:963645050762:android:9e05aea315a4740fd58273',
    messagingSenderId: '963645050762',
    projectId: 'abstask-9bba7',
    storageBucket: 'abstask-9bba7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt-hJSg2b5_nVJClsgqiwUntZkfRqG-kE',
    appId: '1:963645050762:ios:feba8108ac2654a6d58273',
    messagingSenderId: '963645050762',
    projectId: 'abstask-9bba7',
    storageBucket: 'abstask-9bba7.firebasestorage.app',
    iosBundleId: 'com.example.absTask',
  );
}
